### ISSUE TITLE
docker 部署的版本， 如何使用FFmpeg 生成缩略图

### ISSUE THREAD

**Issue by keivenliao** [cloudreve/cloudreve#1764]
docker 部署的版本， 如何使用FFmpeg 生成缩略图

**Comment by aaro-n** [comment]
要自己重新制作Docker镜像，给你个例子：
`docker-compose.yml`
```
version: '3'
services:
  cloudreve:
    build: .
    image: cloudreve-thumbnails
    container_name: cloudreve
    ports:
      - "5212:5212"
```
`Dockerfile`
```
FROM cloudreve/cloudreve:latest
# 同时安装VIPS和FFMpeg，需要保留那个自己选
RUN apk update \
    && apk add --no-cache ffmpeg vips-tools
```
# 简单运行步骤
1.  将`Dockerfile`和`docker-compose.yml`放在同一文件夹
2. 根据文档自己配置，执行`docker-compose up`运行镜像
3. 更新，执行`docker-compose down`停止镜像，执行`docker image prune -a `删除所有未使用镜像，执行`docker-compose up`重新生成镜像，最好自己查查如何使用docker
