### ISSUE TITLE
使用离线下载，转存到OneDrive时报错：Failed to transfer one or more file(s)

### ISSUE THREAD

**Issue by pppfz** [cloudreve/cloudreve#2094]
# 一、部署环境

## 1、cloudreve部署

```yml
networks:
    1panel-network:
        external: true
services:
    cloudreve:
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        image: cloudreve/cloudreve:3.8.3
        labels:
            createdBy: Apps
        networks:
            - 1panel-network
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:5212
        restart: always
        volumes:
            - ./data/uploads:/cloudreve/uploads
            - /tmp/cloudreve:/data   #这里我改过，原来是：./data/data:/data
            - ./data/conf.ini:/cloudreve/conf.ini
            - ./data/cloudreve.db:/cloudreve/cloudreve.db
            - ./data/avatar:/cloudreve/avatar

```

## 2、aria2部署

```yml
version: "3.8"
services:
  Aria2-Pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro:latest
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=zzzzzzzzzzzz
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
    volumes:
      - ./aria2-config:/config   
      - /tmp/cloudreve:/downloads

    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    command: --port 6880 --ipv6
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
```

## 3、cloudreve配置

![image](https://github.com/cloudreve/Cloudreve/assets/119300926/b832d5ea-207b-49d9-99b6-87ae318bd8e6)

# 二、问题

在使用离线下载后，转存到OneDrive时报错：

```txt
Failed to transfer one or more file(s).open/tmp/cloudreve/aria2/e28d56f3-7fca-48c1-b713- 1f0952f0c49d/ZdHxUb2apScBQgvi.mp4:no such file or directory
```

> [[下载测试文件](https://video.twimg.com/ext_tw_video/1806686374441213954/pu/vid/avc1/480x270/ZdHxUb2apScBQgvi.mp4?tag=12)](https://video.twimg.com/ext_tw_video/1806686374441213954/pu/vid/avc1/480x270/ZdHxUb2apScBQgvi.mp4?tag=12)

ariang反馈下载成功：

![image](https://github.com/cloudreve/Cloudreve/assets/119300926/15048318-c6e1-4c26-96fe-4eb28b640ad2)

# 三、部分日志

![image](https://github.com/cloudreve/Cloudreve/assets/119300926/81281384-db19-4b5f-8ba4-f6753c0bbf00)

![image](https://github.com/cloudreve/Cloudreve/assets/119300926/af484313-7610-478e-b9c3-241056210554)

**Comment by fengyi786** [comment]
Failed to transfer one or more file(s).: open /data/cloudreve_temp/aria2/f0bcf1fd-84ca-45a8-9137-b7323475448a/The.Matrix.1999.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265[TGx]/NEW upcoming releases by Xclusive.txt: no such file or directory open
路径中又空格会出现这个情况，需要对路径进行特殊处理

**Comment by 3210448723** [comment]
kimi告诉我这样就可以了，下载目录设置为了`/root/downloads`，用的root用户
docker -compose.yml
```
version: "3.8"
services:
  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve:latest
    restart: unless-stopped
    ports:
      - "5212:5212"

    privileged: true  # 增加
    
    volumes:
      - temp_data:/data
      - ./cloudreve/uploads:/cloudreve/uploads
      - ./cloudreve/conf.ini:/cloudreve/conf.ini
      - ./cloudreve/cloudreve.db:/cloudreve/cloudreve.db
      - ./cloudreve/avatar:/cloudreve/avatar
      
      - /root/downloads:/root/downloads:rw  # 增加
    depends_on:
      - aria2
  aria2:
    container_name: aria2
    image: p3terx/aria2-pro
    restart: unless-stopped
    environment:
      - RPC_SECRET=
      - RPC_PORT=6800
    volumes:
      - ./aria2/config:/config
      - temp_data:/data
volumes:
  temp_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data
      o: bind
```
```
sudo chown -R root:root /root/downloads
sudo chmod -R 777 /root/downloads
```
