### ISSUE TITLE
添加离线下载时aria2无法通信

### ISSUE THREAD

**Issue by xyphllipyx** [cloudreve/Cloudreve#2122]
在NAS上部署使用官方给出的DOCKER命令。
输入参数有误 (Failed to connect to RPC server: Post "http://192.168.8.18:6800/jsonrpc": dial tcp 192.168.8.18:6800: i/o timeout)
aria2 ng能用，我又试了motrix内置的ARIA2能识别，所以这个错误时哪里有问题呢？

**Comment by makebl** [comment]
同样的问题，也是nas

**Comment by 3210448723** [comment]
服务器上我用`ws://公网ip:6800/jsonrpc`就可以连接上，`ws://127.0.0.1:6800/jsonrpc`就不行
![image](https://github.com/user-attachments/assets/76077368-a0cf-4f09-813e-623369c78ab0)

**Comment by 3210448723** [comment]
> @3210448723 aria2的配置是什么样的？
> 
> 是不是位于docker里面部署的

Aria2是用的这个https://github.com/P3TERX/aria2.sh工具安装的
云盘的docker-compose.yml配置如下
```
version: "3.8"
services:
  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve:latest
    restart: unless-stopped
    ports:
      - "5212:5212"
    privileged: true  # 加之前离线下载会报错
    
    volumes:
      - temp_data:/data
      - ./cloudreve/uploads:/cloudreve/uploads
      - ./cloudreve/conf.ini:/cloudreve/conf.ini
      - ./cloudreve/cloudreve.db:/cloudreve/cloudreve.db
      - ./cloudreve/avatar:/cloudreve/avatar
      
      - /root/downloads:/root/downloads:rw  # 加之前离线下载会报错
    depends_on:
      - aria2
  aria2:
    container_name: aria2
    image: p3terx/aria2-pro
    restart: unless-stopped
    environment:
      - RPC_SECRET= #填了密钥
      - RPC_PORT=6800
    volumes:
      - ./aria2/config:/config
      - temp_data:/data
volumes:
  temp_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data
      o: bind
```
