### ISSUE TITLE
升级到 4.1.0，启动失败

### ISSUE THREAD

**Issue by xezzon** [cloudreve/cloudreve#2578]
**Describe the bug**

Docker Compose 运行 4.1.0，启动时报错如下：

```log
[Panic]	 2025-06-27 13:41:01 [/home/vsts/work/1/s/application/dependency/dependency.go:854] Fatal error in dependency initialization: failed to migrate database: Failed creating schema resources: querying server version pq: unsupported sslmode "allow"; only "require" (default), "verify-full", "verify-ca", and "disable" supported
panic: Fatal error in dependency initialization: failed to migrate database: Failed creating schema resources: querying server version pq: unsupported sslmode "allow"; only "require" (default), "verify-full", "verify-ca", and "disable" supported

goroutine 1 [running]:
github.com/cloudreve/Cloudreve/v4/pkg/logging.NewConsoleLogger.func2(0xc0000b3d80, {0x1fd019b?, 0x4108e5?}, {0xc00089a530?, 0x1c29800?, 0xc000408e01?})
	/home/vsts/work/1/s/pkg/logging/logger.go:59 +0x75
github.com/cloudreve/Cloudreve/v4/pkg/logging.(*consoleLogger).Panic(0x2fbddd0?, {0x1fd019b?, 0xc0008a60a0?}, {0xc00089a530?, 0xc0003fb850?, 0x2f9a084?})
	/home/vsts/work/1/s/pkg/logging/logger.go:111 +0x23
github.com/cloudreve/Cloudreve/v4/application/dependency.(*dependency).panicError(...)
	/home/vsts/work/1/s/application/dependency/dependency.go:854
github.com/cloudreve/Cloudreve/v4/application/dependency.(*dependency).DBClient(0xc000972848)
	/home/vsts/work/1/s/application/dependency/dependency.go:315 +0x243
github.com/cloudreve/Cloudreve/v4/application.(*server).Start(0xc000907680)
	/home/vsts/work/1/s/application/application.go:82 +0x1c5
github.com/cloudreve/Cloudreve/v4/cmd.init.func4(0xc000119d00?, {0x1f6cdd6?, 0x4?, 0x1f6cce6?})
	/home/vsts/work/1/s/cmd/server.go:44 +0x3da
github.com/spf13/cobra.(*Command).execute(0x40dbc60, {0x412f040, 0x0, 0x0})
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x40db980)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/cloudreve/Cloudreve/v4/cmd.Execute()
	/home/vsts/work/1/s/cmd/root.go:38 +0x25f
main.main()
	/home/vsts/work/1/s/main.go:27 +0xf
```

**To Reproduce**

使用 Docker Compose 运行以下文件：

```yaml
services:
  cloudreve:
    image: cloudreve/cloudreve:4.1.0
    restart: always
    ports:
      - 5212:5212
    environment:
      - CR_CONF_Database.Type=postgres
      - CR_CONF_Database.Host=***
      - CR_CONF_Database.Name=***
      - CR_CONF_Database.User=***
      - CR_CONF_Database.Password=***
      - CR_CONF_Database.Port=5432
      - CR_CONF_Redis.Server=***:6379
      - CR_CONF_Redis.Password=***
    volumes:
      - ./data:/cloudreve/data
```

**Expected behavior**

正常启动应用。

**Additional context**

- #2540
- lib/pq#776
